var languageNamespace ={
    'en ': 'English',
    'ceb ': 'Sinugboanong Binisaya',
    'sv ': 'Svenska',
    'de ': 'Deutsch',
    'fr ': 'Français',
    'nl ': 'Nederlands',
    'ru ': 'Русский',
    'it ': 'Italiano',
    'es ': 'Español',
    'pl ': 'Polski',
    'arz ': 'مصرى (Maṣri)',
    'ja ': '日本語',
    'war ': 'Winaray',
    'vi ': 'Tiếng Việt',
    'zh ': '中文',
    'ar ': 'العربية',
    'uk ': 'Українська',
    'pt ': 'Português',
    'fa ': 'فارسی',
    'ca ': 'Català',
    'sr ': 'Српски / Srpski',
    'id ': 'Bahasa Indonesia',
    'no ': 'Norsk (Bokmål)',
    'ko ': '한국어',
    'fi ': 'Suomi',
    'hu ': 'Magyar',
    'cs ': 'Čeština',
    'sh ': 'Srpskohrvatski / Српскохрватски',
    'zh-min-nan ': 'Bân-lâm-gú',
    'ro ': 'Română',
    'tr ': 'Türkçe',
    'eu ': 'Euskara',
    'ce ': 'Нохчийн',
    'ms ': 'Bahasa Melayu',
    'eo ': 'Esperanto',
    'he ': 'עברית',
    'hy ': 'Հայերեն',
    'tt ': 'Tatarça / Татарча',
    'bg ': 'Български',
    'da ': 'Dansk',
    'azb ': 'تۆرکجه',
    'sk ': 'Slovenčina',
    'kk ': 'Қазақша',
    'min ': 'Minangkabau',
    'et ': 'Eesti',
    'hr ': 'Hrvatski',
    'be ': 'Беларуская',
    'lt ': 'Lietuvių',
    'el ': 'Ελληνικά',
    'simple ': 'Simple English',
    'az ': 'Azərbaycanca',
    'gl ': 'Galego',
    'sl ': 'Slovenščina',
    'ur ': 'اردو',
    'nn ': 'Nynorsk',
    'ka ': 'ქართული',
    'hi ': 'हिन्दी',
    'uz ': 'O‘zbek',
    'th ': 'ไทย',
    'ta ': 'தமிழ்',
    'la ': 'Latina',
    'cy ': 'Cymraeg',
    'ast ': 'Asturianu',
    'vo ': 'Volapük',
    'mk ': 'Македонски',
    'zh-yue ': '粵語',
    'bn ': 'বাংলা',
    'lv ': 'Latviešu',
    'tg ': 'Тоҷикӣ',
    'my ': 'မြန်မာဘာသာ',
    'af ': 'Afrikaans',
    'mg ': 'Malagasy',
    'oc ': 'Occitan',
    'bs ': 'Bosanski',
    'sq ': 'Shqip',
    'nds ': 'Plattdüütsch',
    'ky ': 'Кыргызча',
    'mr ': 'मराठी',
    'be-tarask ': 'Беларуская (тарашкевіца)',
    'ml ': 'മലയാളം',
    'new ': 'नेपाल भाषा',
    'te ': 'తెలుగు',
    'br ': 'Brezhoneg',
    'vec ': 'Vèneto',
    'pms ': 'Piemontèis',
    'jv ': 'Basa Jawa',
    'sw ': 'Kiswahili',
    'pnb ': 'شاہ مکھی پنجابی (Shāhmukhī Pañjābī)',
    'ht ': 'Krèyol ayisyen',
    'su ': 'Basa Sunda',
    'lb ': 'Lëtzebuergesch',
    'ba ': 'Башҡорт',
    'ga ': 'Gaeilge',
    'szl ': 'Ślůnski',
    'is ': 'Íslenska',
    'tl ': 'Tagalog',
    'lmo ': 'Lumbaart',
    'cv ': 'Чăваш',
    'fy ': 'Frysk',
    'wuu ': '吴语',
    'sco ': 'Scots',
    'an ': 'Aragonés',
    'diq ': 'Zazaki',
    'ku ': 'Kurdî / كوردی',
    'pa ': 'ਪੰਜਾਬੀ',
    'yo ': 'Yorùbá',
    'ne ': 'नेपाली',
    'bar ': 'Boarisch',
    'ckb ': 'Soranî / کوردی',
    'io ': 'Ido',
    'gu ': 'ગુજરાતી',
    'als ': 'Alemannisch',
    'kn ': 'ಕನ್ನಡ',
    'scn ': 'Sicilianu',
    'bpy ': 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী',
    'ia ': 'Interlingua',
    'qu ': 'Runa Simi',
    'mn ': 'Монгол',
    'si ': 'සිංහල',
    'bat-smg ': 'Žemaitėška',
    'nv ': 'Diné bizaad',
    'xmf ': 'მარგალური (Margaluri)',
    'or ': 'ଓଡ଼ିଆ',
    'cdo ': 'Mìng-dĕ̤ng-ngṳ̄',
    'ilo ': 'Ilokano',
    'gd ': 'Gàidhlig',
    'yi ': 'ייִדיש',
    'am ': 'አማርኛ',
    'nap ': 'Nnapulitano',
    'avk ': 'Kotava',
    'sd ': 'سنڌي، سندھی ، सिन्ध',
    'bug ': 'Basa Ugi',
    'hsb ': 'Hornjoserbsce',
    'mai ': 'मैथिली',
    'fo ': 'Føroyskt',
    'os ': 'Иронау',
    'map-bms ': 'Basa Banyumasan',
    'li ': 'Limburgs',
    'frr ': 'Nordfriisk',
    'mzn ': 'مَزِروني',
    'sah ': 'Саха тыла (Saxa Tyla)',
    'eml ': 'Emiliàn e rumagnòl',
    'ps ': 'پښتو',
    'ace ': 'Basa Acèh',
    'sa ': 'संस्कृतम्',
    'gor ': 'Hulontalo',
    'bcl ': 'Bikol',
    'wa ': 'Walon',
    'zh-classical ': '古文 / 文言文',
    'lij ': 'Lìgure',
    'mrj ': 'Кырык Мары (Kyryk Mary)',
    'crh ': 'Qırımtatarca',
    'mhr ': 'Олык Марий (Olyk Marij)',
    'hif ': 'Fiji Hindi',
    'hak ': 'Hak-kâ-fa / 客家話',
    'roa-tara ': 'Tarandíne',
    'ha ': 'Hausa / هَوُسَ',
    'shn ': 'လိၵ်ႈတႆး',
    'pam ': 'Kapampangan',
    'hyw ': 'Արեւմտահայերէն',
    'as ': 'অসমীয়া',
    'nso ': 'Sepedi',
    'km ': 'ភាសាខ្មែរ',
    'ie ': 'Interlingue',
    'rue ': 'Русиньскый',
    'zu ': 'isiZulu',
    'ban ': 'Bali',
    'se ': 'Sámegiella',
    'bh ': 'भोजपुरी',
    'vls ': 'West-Vlams',
    'nds-nl ': 'Nedersaksisch',
    'mi ': 'Māori',
    'sc ': 'Sardu',
    'nah ': 'Nāhuatl',
    'sn ': 'chiShona',
    'vep ': 'Vepsän',
    'gan ': '贛語',
    'myv ': 'Эрзянь (Erzjanj Kelj)',
    'glk ': 'گیلکی',
    'kab ': 'Taqbaylit',
    'sat ': 'ᱥᱟᱱᱛᱟᱲᱤ',
    'so ': 'Soomaali',
    'ab ': 'Аԥсуа',
    'bo ': 'བོད་སྐད',
    'co ': 'Corsu',
    'tk ': 'Türkmen',
    'fiu-vro ': 'Võro',
    'kv ': 'Коми',
    'csb ': 'Kaszëbsczi',
    'pcd ': 'Picard',
    'frp ': 'Arpetan',
    'udm ': 'Удмурт кыл',
    'ug ': 'ئۇيغۇر تىلى',
    'gv ': 'Gaelg',
    'ay ': 'Aymar',
    'zea ': 'Zeêuws',
    'kw ': 'Kernowek/Karnuack',
    'nrm ': 'Nouormand/Normaund',
    'lez ': 'Лезги чІал (Lezgi č’al)',
    'lfn ': 'Lingua franca nova',
    'gn ': 'Avañe'ẽ',
    'stq ': 'Seeltersk',
    'mt ': 'Malti',
    'mni ': 'ꯃꯤꯇꯩꯂꯣꯟ',
    'ary ': 'الدارجة',
    'mwl ': 'Mirandés',
    'rm ': 'Rumantsch',
    'lo ': 'ລາວ',
    'skr ': 'سرائیکی',
    'bjn ': 'Bahasa Banjar',
    'olo ': 'Karjalan',
    'lad ': 'Dzhudezmo',
    'gom ': 'गोंयची कोंकणी / Gõychi Konknni',
    'koi ': 'Перем Коми (Perem Komi)',
    'fur ': 'Furlan',
    'ang ': 'Englisc',
    'dty ': 'डोटेली',
    'dsb ': 'Dolnoserbski',
    'ext ': 'Estremeñu',
    'ln ': 'Lingala',
    'tyv ': 'Тыва',
    'cbk-zam ': 'Chavacano de Zamboanga',
    'dv ': 'ދިވެހިބަސް',
    'smn ': 'Anarâškielâ',
    'ksh ': 'Ripoarisch',
    'gag ': 'Gagauz',
    'pfl ': 'Pälzisch',
    'pag ': 'Pangasinan',
    'pi ': 'पाऴि',
    'av ': 'Авар',
    'awa ': 'अवधी',
    'bxr ': 'Буряад',
    'tay ': 'Tayal',
    'haw ': 'Hawaiʻi',
    'pap ': 'Papiamentu',
    'ig ': 'Ìgbò',
    'xal ': 'Хальмг',
    'rw ': 'Ikinyarwanda',
    'krc ': 'Къарачай-Малкъар (Qarachay-Malqar)',
    'za ': 'Cuengh',
    'pdc ': 'Deitsch',
    'kaa ': 'Qaraqalpaqsha',
    'szy ': 'Sakizaya',
    'inh ': 'ГӀалгӀай',
    'arc ': 'ܐܪܡܝܐ',
    'to ': 'faka Tonga',
    'nov ': 'Novial',
    'kbp ': 'Kabɩyɛ',
    'jam ': 'Jumiekan Kryuol',
    'wo ': 'Wolof',
    'tpi ': 'Tok Pisin',
    'na ': 'dorerin Naoero',
    'kbd ': 'Адыгэбзэ (Adighabze)',
    'atj ': 'Atikamekw',
    'ki ': 'Gĩkũyũ',
    'tet ': 'Tetun',
    'tcy ': 'ತುಳು',
    'ak ': 'Akana',
    'lld ': 'Lingaz',
    'lg ': 'Luganda',
    'jbo ': 'Lojban',
    'bi ': 'Bislama',
    'roa-rup ': 'Armãneashce',
    'lbe ': 'Лакку',
    'kg ': 'Kikôngo',
    'ty ': 'Reo Mā`ohi',
    'mdf ': 'Мокшень (Mokshanj Kälj)',
    'xh ': 'isiXhosa',
    'fj ': 'Na Vosa Vakaviti',
    'srn ': 'Sranantongo',
    'om ': 'Oromoo',
    'gcr ': 'Kriyòl Gwiyannen',
    'trv ': 'Taroko',
    'ltg ': 'Latgaļu',
    'sm ': 'Gagana Samoa',
    'chr ': 'ᏣᎳᎩ',
    'nia ': 'Li Niha',
    'nqo ': 'ߒߞߏ',
    'pih ': 'Norfuk',
    'mnw ': 'မန်',
    'got ': '𐌲𐌿𐍄𐌹𐍃𐌺',
    'st ': 'Sesotho',
    'kl ': 'Kalaallisut',
    'mad ': 'Madhurâ',
    'tw ': 'Twi',
    'cu ': 'Словѣньскъ',
    'ny ': 'Chichewa',
    'tn ': 'Setswana',
    'ts ': 'Xitsonga',
    'bm ': 'Bamanankan',
    'rmy ': 'romani - रोमानी',
    've ': 'Tshivenda',
    'chy ': 'Tsetsêhestâhese',
    'rn ': 'Ikirundi',
    'tum ': 'chiTumbuka',
    'iu ': 'ᐃᓄᒃᑎᑐᑦ',
    'ss ': 'SiSwati',
    'ch ': 'Chamoru',
    'ks ': 'कश्मीरी / كشميري',
    'alt ': 'Алтай',
    'pnt ': 'Ποντιακά',
    'ady ': 'Адыгэбзэ',
    'ee ': 'Eʋegbe',
    'ff ': 'Fulfulde',
    'ik ': 'Iñupiatun',
    'sg ': 'Sängö',
    'din ': 'Thuɔŋjäŋ',
    'dz ': 'ཇོང་ཁ',
    'ti ': 'ትግርኛ',
    'cr ': 'Nehiyaw',
    'ng ': 'Ndonga',
    'cho ': 'Choctaw',
    'kj ': 'Kuanyama',
    'mh ': 'Ebon',
    'ho ': 'Hiri Motu',
    'ii ': 'ꆇꉙ',
    'aa ': 'Afar',
    'lrc ': 'لۊری شومالی',
    'mus ': 'Muskogee',
};
var translation = {
	'en':{
		'step1':'Enter article name',
		'step2':'Place the peg on the edit to play',
		'step3':'Click Play',
		'step4':'Enjoy viewing edits',
		'overlayLoadButton':'Show History',
		'headerLoadButton':'Show History',
		'projectHome':'What is Replay Edits',
		'overlayInputPlaceHolder':'Enter article name',
		'headerInputPlaceHolder':'Enter article name',
		'control-1':'Speed',
		'control-2':'Play/pause',
		'errorMessage':'Article does not exist'
	},
	'nl':{
		'step1':'Voer artikel naam',
		'step2':'Plaats de pin op de bewerking te spelen',
		'step3':'Klik op Afspelen',
		'step4':'Geniet van het bekijken edits',
		'overlayLoadButton':'Toon Geschiedenis',
		'headerLoadButton':'Toon Geschiedenis',
		'projectHome':'Wat is Replay Edits',
		'overlayInputPlaceHolder':'Voer artikel naam',
		'headerInputPlaceHolder':'Voer artikel naam',
		'control-1':'Snelheid',
		'control-2':'Afspelen/Pauzeren',
		'errorMessage':'Artikel bestaat niet'
	},
	'es':{
		'step1':'Introduzca el nombre del artículo',
		'step2':'Coloque la clavija en la edición de jugar',
		'step3':'Haga clic en Reproducir',
		'step4':'Geniet van het bekijken edits',
		'overlayLoadButton':'Mostrar Historia',
		'headerLoadButton':'Mostrar Historia',
		'projectHome':'Cuál es ediciones de reproducción',
		'overlayInputPlaceHolder':'Introduzca el nombre del artículo',
		'headerInputPlaceHolder':'Introduzca el nombre del artículo',
		'control-1':'Velocidad',
		'control-2':'Reproducir/Pausa',
		'errorMessage':'No existe el artículo'
	},
	'fr':{
		'step1':"Entrez un nom d'article",
		'step2':'Placez la cheville sur la modification de jouer',
		'step3':'Cliquez sur Lecture',
		'step4':"Profitez de modifications d'affichage",
		'overlayLoadButton':"Afficher l'historique",
		'headerLoadButton':"Afficher l'historique",
		'projectHome':"Qu'est-ce que les modifications de relecture",
		'overlayInputPlaceHolder':"Entrez un nom d'article",
		'headerInputPlaceHolder':"Entrez un nom d'article",
		'control-1':'Vitesse',
		'control-2':'Lecture/Pause',
		'errorMessage':"L'article n'existe pas"
	},
	'it':{
		'step1':"Inserire il nome articolo",
		'step2':'Posizionare il piolo sulla modifica per giocare',
		'step3':'Fare clic su Riproduci',
		'step4':"Godetevi le modifiche di visualizzazione",
		'overlayLoadButton':"Mostra Storia",
		'headerLoadButton':"Mostra Storia",
		'projectHome':"Che cosa è modifiche di replay",
		'overlayInputPlaceHolder':"Inserire il nome articolo",
		'headerInputPlaceHolder':"Inserire il nome articolo",
		'control-1':'Velocità',
		'control-2':'Play/Pausa',
		'errorMessage':"L'articolo non esiste"
	},
	'de':{
		'step1':'Geben Sie Artikelnamen',
		'step2':'Legen Sie den Stift auf der Bearbeitungs zu spielen',
		'step3':'Klicken Sie auf Wiedergabe',
		'step4':'Genießen Sie die Änderungen',
		'overlayLoadButton':'Verlauf anzeigen ',
		'headerLoadButton':'Verlauf anzeigen ',
		'projectHome':'Was ist Replay Bearbeitungen',
		'overlayInputPlaceHolder':'Geben Sie Artikelnamen',
		'headerInputPlaceHolder':'Geben Sie Artikelnamen',
		'control-1':'Geschwindigkeit',
		'control-2':'Wiedergabe/Pause',
		'errorMessage':'Artikel existiert nicht'
	},
	'ru':{
		'step1':'Введите имя статьи',
		'step2':'Поместите колышек на редактирование играть',
		'step3':'Нажмите кнопку Воспроизведение',
		'step4':'Насладитесь просмотром правки',
		'overlayLoadButton':'Показать историю',
		'headerLoadButton':'Показать историю',
		'projectHome':'Что такое переиграть правки',
		'overlayInputPlaceHolder':'Введите имя статьи',
		'headerInputPlaceHolder':'Введите имя статьи',
		'control-1':'скорость',
		'control-2':'Воспроизведение/пауза',
		'errorMessage':'Статья не существует'
	},
	'ja':{
		'step1':'品名を入力してください ',
		'step2':'プレイするには、編集上のペグを配置',
		'step3':'[再生]をクリックします ',
		'step4':'閲覧編集を楽しむ ',
		'overlayLoadButton':'履歴を表示',
		'headerLoadButton':'履歴を表示',
		'projectHome':'リプレイ編集とは何ですか ',
		'overlayInputPlaceHolder':'品名を入力してください ',
		'headerInputPlaceHolder':'品名を入力してください ',
		'control-1':'スピード ',
		'control-2':'再生/一時停止',
		'errorMessage':'記事は存在しません'
	},
	'zh':{
		'step1':'输入条目名称',
		'step2':'用指针选择历史中的编辑',
		'step3':'点击播放',
		'step4':'开始观看编辑',
		'overlayLoadButton':'显示历史',
		'headerLoadButton':'显示历史',
		'projectHome':'什么是编辑重现',
		'overlayInputPlaceHolder':'输入条目名称',
		'headerInputPlaceHolder':'输入条目名称',
		'control-1':'速度',
		'control-2':'播放/暂停',
		'errorMessage':'条目不存在'
	},
	'pl':{
		'step1':'Wpisz nazwę artykułu',
		'step2':'Umieść kołek na edycji grać',
		'step3':'Kliknij przycisk Odtwórz',
		'step4':'Ciesz oglądania zmiany',
		'overlayLoadButton':'Pokaż Historię',
		'headerLoadButton':'Pokaż Historię',
		'projectHome':'Co to jest edycje replay',
		'overlayInputPlaceHolder':'Wpisz nazwę artykułu',
		'headerInputPlaceHolder':'Wpisz nazwę artykułu',
		'control-1':'prędkość',
		'control-2':'Play/Pause',
		'errorMessage':'Artykuł nie istnieje'
	},
	'pt':{
		'step1':'Digite o nome do artigo',
		'step2':'Coloque o pino na edição para jogar',
		'step3':'Clique em Play',
		'step4':'Desfrute edições visualização',
		'overlayLoadButton':'Mostrar Histórico',
		'headerLoadButton':'Mostrar Histórico',
		'projectHome':'O que é edições de replay',
		'overlayInputPlaceHolder':'Digite o nome do artigo',
		'headerInputPlaceHolder':'Digite o nome do artigo',
		'control-1':'Velocidade',
		'control-2':'Reproduzir/Pausar',
		'errorMessage':'O artigo não existe'
	},
	'sv':{
		'step1':'Indtast artiklen navn',
		'step2':'Placer pind på Rediger for at spille',
		'step3':'Klik på Afspil',
		'step4':'Nyd visning redigeringer',
		'overlayLoadButton':'Vis Historik',
		'headerLoadButton':'Vis Historik',
		'projectHome':'Hvad er replay redigeringer',
		'overlayInputPlaceHolder':'Indtast artiklen navn',
		'headerInputPlaceHolder':'Indtast artiklen navn',
		'control-1':'Hastighed',
		'control-2':'Afspil/Pause',
		'errorMessage':'Artikel findes ikke'
	},
	'fi':{
		'step1':'Anna artikkelin nimi',
		'step2':'Aseta kursori muokkauksen kohdalle ja käynnistä',
		'step3':'Paina Käynnistä',
		'step4':'Nauti muokkausten katselusta',
		'overlayLoadButton':'Näytä historia',
		'headerLoadButton':'Näytä historia',
		'projectHome':'Mikä on Replay Edit',
		'overlayInputPlaceHolder':'Anna artikkelin nimi',
		'headerInputPlaceHolder':'Anna artikkelin nimi',
		'control-1':'Nopeus',
		'control-2':'Käynnistä/Pysäytä',
		'errorMessage':'Artikkelia ei ole olemassa'
	},
	'se':{
		'step1':'Anna artikkelin nimi',
		'step2':'Aseta kursori muokkauksen kohdalle ja käynnistä',
		'step3':'Paina Käynnistä',
		'step4':'Nauti muokkausten katselusta',
		'overlayLoadButton':'Näytä historia',
		'headerLoadButton':'Näytä historia',
		'projectHome':'Mikä on Replay Edit',
		'overlayInputPlaceHolder':'Anna artikkelin nimi',
		'headerInputPlaceHolder':'Anna artikkelin nimi',
		'control-1':'Nopeus',
		'control-2':'Käynnistä/Pysäytä',
		'errorMessage':'Artikkelia ei ole olemassa'
	},
	'smn':{
		'step1':'Anna artikkelin nimi',
		'step2':'Aseta kursori muokkauksen kohdalle ja käynnistä',
		'step3':'Paina Käynnistä',
		'step4':'Nauti muokkausten katselusta',
		'overlayLoadButton':'Näytä historia',
		'headerLoadButton':'Näytä historia',
		'projectHome':'Mikä on Replay Edit',
		'overlayInputPlaceHolder':'Anna artikkelin nimi',
		'headerInputPlaceHolder':'Anna artikkelin nimi',
		'control-1':'Nopeus',
		'control-2':'Käynnistä/Pysäytä',
		'errorMessage':'Artikkelia ei ole olemassa'
	},
	'fo':{
		'step1':'Enter article name',
		'step2':'Place the peg on the edit to play',
		'step3':'Click Play',
		'step4':'Enjoy viewing edits',
		'overlayLoadButton':'Show History',
		'headerLoadButton':'Show History',
		'projectHome':'What is Replay Edits',
		'overlayInputPlaceHolder':'Enter article name',
		'headerInputPlaceHolder':'Enter article name',
		'control-1':'Speed',
		'control-2':'Play/pause',
		'errorMessage':'Article does not exist'
	},
	'no':{
		'step1':'Skriv inn artikkelnavnet ',
		'step2':'Sett pinnen på redigerings å spille',
		'step3':'Klikk Play',
		'step4':'Nyt ser edits',
		'overlayLoadButton':'Vis History',
		'headerLoadButton':'Vis History',
		'projectHome':'Hva er replay edits',
		'overlayInputPlaceHolder':'Skriv inn artikkelnavnet',
		'headerInputPlaceHolder':'Skriv inn artikkelnavnet',
		'control-1':'Fart',
		'control-2':'Play/Pause',
		'errorMessage':'Artikkel eksisterer ikke'
	},
	'hi':{
		'step1':'लेख का नाम दर्ज करें',
		'step2':'खेलने के लिए संपादित करें पर खूंटी रखें',
		'step3':'प्ले पर क्लिक करें',
		'step4':'देखने के संपादन का आनंद लें',
		'overlayLoadButton':'इतिहास दिखाएं',
		'headerLoadButton':'इतिहास दिखाएं',
		'projectHome':'फिर से खेलना संपादन क्या है',
		'overlayInputPlaceHolder':'लेख का नाम दर्ज करें',
		'headerInputPlaceHolder':'लेख का नाम दर्ज करें',
		'control-1':'गति',
		'control-2':'खेल/ठहराव',
		'errorMessage':'लेख मौजूद नहीं है'
	},
	'te':{
		'step1':'వ్యాసం పేరు నమోదు ',
		'step2':'ఆటను సవరణపై పెగ్ ఉంచండి ',
		'step3':'ప్లే క్లిక్ చేయండి ',
		'step4':'వీక్షణ సవరణలు ఆనందించండి ',
		'overlayLoadButton':'చరిత్రను చూపించు ',
		'headerLoadButton':'చరిత్రను చూపించు ',
		'projectHome':'రీప్లే సవరణలు ఏమిటి ',
		'overlayInputPlaceHolder':'వ్యాసం పేరు నమోదు ',
		'headerInputPlaceHolder':'వ్యాసం పేరు నమోదు ',
		'control-1':'వేగము ',
		'control-2':'ప్లే / పాజ్ ',
		'errorMessage':'వ్యాసం లేదు'
	},
	'ta':{
		'step1':'கட்டுரை பெயர் சேர்க்கவும்',
		'step2':'விளையாட தொகு மீது மது வைக்க',
		'step3':'ப்ளே சொடுக்கவும்',
		'step4':'பார்க்கும் தொகுப்புகளின் அனுபவிக்க',
		'overlayLoadButton':'வரலாறு காட்டு',
		'headerLoadButton':'வரலாறு காட்டு',
		'projectHome':'மறு திருத்தங்கள் என்ன',
		'overlayInputPlaceHolder':'கட்டுரை பெயர் சேர்க்கவும்',
		'headerInputPlaceHolder':'கட்டுரை பெயர் சேர்க்கவும்',
		'control-1':'வேகம்',
		'control-2':'நாடகம்/இடைநிறுத்தப்பட்டு',
		'errorMessage':'கட்டுரை இல்லை'
	},
	'ml':{
		'step1':'ലേഖനത്തിന്റെ പേരെഴുതൂ',
		'step2':'പ്രവർത്തിപ്പിക്കാനായി തിരുത്തലിനു മുകളിലേക്ക് പെഗ് നീക്കൂ',
		'step3':'പ്രവർത്തിപ്പിക്കാനായി ഞെക്കുക',
		'step4':'തിരുത്തലുകൾ കാണൂ',
		'overlayLoadButton':'നാൾവഴി കാണിക്കുക',
		'headerLoadButton':'നാൾവഴി കാണിക്കുക',
		'projectHome':'തിരുത്ത് പുനർദർശിനി എന്താണ്',
		'overlayInputPlaceHolder':'ലേഖനത്തിന്റെ പേര് നൽകുക',
		'headerInputPlaceHolder':'ലേഖനത്തിന്റെ പേര് നൽകുക',
		'control-1':'വേഗത',
		'control-2':'പ്രവർത്തിപ്പിക്കുക/നിർത്തുക',
		'errorMessage':'ലേഖനം നിലവിലില്ല'
	},
	'kn':{
		'step1':'ಲೇಖನದ ಹೆಸರು ಬರೆಯಿರಿ',
		'step2':'ಚಲಿಸುವುದಕ್ಕಾಗಿ ಸಂಪಾದನದ ಮೇಲೆ ಪೆಗ್ ಹಾಕಿ',
		'step3':'ಪ್ಲೇ ಕ್ಲಿಕ್ ಮಾಡಿ',
		'step4':'ಸಂಪಾದನಗಳು ವೀಕ್ಷಿಸಿ',
		'overlayLoadButton':'ಇತಿಹಾಸ ತೋರಿಸಿ',
		'headerLoadButton':'ಇತಿಹಾಸ ತೋರಿಸಿ',
		'projectHome':'ಸಂಪಾದನ ಪುನಃದರ್ಶಿನಿ ಎದರೇನು',
		'overlayInputPlaceHolder':' ಲೇಖನದ ಹೆಸರು ಬರೆಯಿರಿ',
		'headerInputPlaceHolder':' ಲೇಖನದ ಹೆಸರು ಬರೆಯಿರಿ',
		'control-1':'ವೇಗ',
		'control-2':'ಚಲಿಸಿ/ತಡೆ',
		'errorMessage':'ಈ ಲೇಖನ ವಿಕಿಪೀಡಿಯದಲ್ಲಿ ಇಲ್ಲ'
	}
};
